name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        family: medusa-task
        container-name: medusa-backend
        image: ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        cluster:aws_ecs_cluster.main.id 
        service: aws_ecs_service
        wait-for-service-stability: true

